services:
  jekyll:
    build: .
    container_name: jimmygleason.com-jekyll-local
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
      - TZ=America/Los_Angeles
      - JEKYLL_USE_POLLING=true
    logging:
      driver: syslog
      options: 
        syslog-address: "udp://172.17.0.4:1514"
        syslog-format: "rfc3164"
        tag: jekyll-local
